### ISSUE TITLE
Confused about the v5.0 release notes

### ISSUE THREAD

**Issue by WillStrohl** [redtempo/dnnstuff.sqlviewpro#3]
Reference:  https://redtempo.github.io/dnnstuff.sqlviewpro/releases

Each of these sentences alone doesn't really describe to me what I may have to do before an upgrade:

- Quotes around report parameters, query string parameters and form parameters
- Multi valued parameters

Is there an example of what we're supposed to do with this?  Also, I'm fairly new to this module.  What do you mean by a "multi-valued parameter?"

- multi-valued parameters will now need to be handled within a stored procedure. The multi-valued parameter will be passed as a single comma-separated value

**Comment by richard-edwards** [comment]
### Multivalued parameters
* A multivalued parameter is created from a parameter that can have multiple values like a select list. In previous versions you could do ```WHERE Department IN ([PARAMETER:Department])``` and it would be handled but now you need to pass to a stored proc like ```exec myProc [PARAMETER:Department]``` instead of just a regular adhoc query

### Quotes around parameters
* Previously you needed to surround your parameters with single quotes for strings etc. but now you can just use the parameter without the single quotes

**Comment by WillStrohl** [comment]
Thanks for the clarification
